### ISSUE TITLE
Guidance on forks, branches and PRs

### ISSUE THREAD

**Issue by vvcb** [MattStammers/hdruk_avoidable_admissions_collaboration_docs#1]
Hi @MattStammers , 

How would you like the various sites/contributors to work with this repo? I think forking and creating PRs would be an obvious one. 

With regards to branching there are a few options:

1. All working off the `main` branch but using a pragmatic file/folder naming/usage discipline to avoid too many conflicts 
2. A branch per site, with teams at each site using their own branch as their local `dev` branch

There are pros and cons with both approaches. In either case, you will approve pull requests.  

At LTH, we will go with Option 2 for now but happy to merge on main before generating a PR if you decide to go with Option 1.

Apologies if this sounds overcomplicated - but looks like a large team will be working collaboratively - so some guidance will be useful.

**Comment by ccarenzoIC** [comment]
Imperial also will go with option 2 (icht branch)

**Comment by MattStammers** [comment]
Yes, this is what we were thinking - branches per site and forks as needed. I suspect it will get messier before it gets better. Probably the only way to work it out

**Comment by MattStammers** [comment]
It looks like we are heading towards having a beginner and advanced pipeline to choose from. Ideally we can bring them together into one. Let's see what we can pull together
