### ISSUE TITLE
Research Date Ranges

### ISSUE THREAD

**Issue by quindavies** [MattStammers/hdruk_avoidable_admissions_collaboration_docs#3]
Double checking the 13 month time period (01-08-21 - 31-08-22) is correct and not supposed to be 12 months

https://github.com/MattStammers/hdruk_avoidable_admissions_collaboration_docs/blob/main/docs/index.md?plain=1#L34

**Comment by RicCampbell** [comment]
Good spot, the study period of interest should be 2021-10-01 to 2022-09-30, which is stated in the data specification that was sent to sites.

It's also worth noting that the population is slightly different what is mentioned on the index page, as that is only for the Emergency Care dataset. For the Admitted Patient Care dataset we are interested in 'all acute emergency admissions for adults (18 years + on day of admission) that had an admission date within the specified study period'.

Hope this helps.

**Comment by MattStammers** [comment]
Pull request has been approved for merge to main.
